name: vbaseproject
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  flutter_riverpod: ^2.1.3
  responsive_builder: ^0.7.0
  responsive_framework: ^1.1.0
  syncfusion_flutter_pdfviewer: ^22.2.11
  webview_flutter: ^4.0.2
  lottie: ^2.6.0

  #core
  cached_network_image: ^3.2.3

  #util
  uuid: any
  flutter_image_compress: ^2.0.4
  image: ^4.0.17

  #firebase
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  firebase_remote_config: ^4.2.5
  firebase_analytics: ^10.4.5
  firebase_messaging: ^14.6.7
  cloud_firestore: ^4.4.2
  firebase_crashlytics: ^3.3.5

  #database
  shared_preferences: ^2.2.1

  #package
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  share_plus: ^7.1.0
  screenshot: ^2.1.0
  path_provider: ^2.1.1

  # ui
  dotted_border: ^2.0.0+3
  shimmer: ^3.0.0
  sliver_snap: ^1.2.0
  font_awesome_flutter: ^10.5.0
  kartal: ^3.4.1

  # JSON
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  logger: ^2.0.1
  json_serializable: ^6.6.1
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/product/generated/
  integrations:
    lottie: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/
    - assets/docs/
    - assets/lottie/
    - assets/images/
