name: vbaseproject
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  flutter_riverpod: ^2.1.3
  responsive_builder: ^0.7.0
  responsive_framework: ^1.1.0
  syncfusion_flutter_pdfviewer: ^22.2.11
  webview_flutter: ^4.0.2
  lottie: ^2.6.0

  #third-party
  app_settings: ^5.1.1
  permission_handler: ^11.0.0

  #core
  cached_network_image: ^3.2.3
  get_it: ^7.6.4

  #util
  uuid: any
  flutter_image_compress: ^2.0.4
  image: ^4.0.17
  google_fonts: ^6.1.0

  #firebase
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  firebase_remote_config: ^4.2.5
  firebase_analytics: ^10.5.0
  firebase_messaging: ^14.6.7
  cloud_firestore: ^4.4.2
  firebase_crashlytics: ^3.3.6
  firebase_ui_firestore: ^1.5.11

  #database
  shared_preferences: ^2.2.1

  #package
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  share_plus: ^7.1.0
  screenshot: ^2.1.0
  path_provider: ^2.1.1
  add_2_calendar: ^2.2.4

  # ui
  dotted_border: ^2.0.0+3
  shimmer: ^3.0.0
  sliver_snap: ^1.2.0
  font_awesome_flutter: ^10.5.0
  kartal: ^3.4.2
  carousel_slider: ^4.2.1
  flutter_speed_dial: ^7.0.0

  # JSON
  json_annotation: ^4.8.0

  life_shared:
    git:
      url: https://github.com/VB-CORE/life_shared.git

  file_picker: ^5.5.0

dependency_overrides:
  kartal:
    git:
      url: https://github.com/VB10/kartal

  connectivity_plus:
    git:
      url: https://github.com/fluttercommunity/plus_plugins
      path: packages/connectivity_plus/connectivity_plus
      ref: cf7d93fbfc76830acf2db755543cf4235a49df60

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  logger: ^2.0.1
  json_serializable: ^6.6.1
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/product/generated/
  integrations:
    lottie: true

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/app/app_icon.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/
    - assets/docs/
    - assets/lottie/
    - assets/images/
