name: lifeclient
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 4.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: 6.1.0
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  equatable: ^2.0.5

  #Core
  get_it: ^8.0.0

  #state management
  flutter_riverpod: ^2.4.8
  riverpod_annotation: ^2.3.2

  responsive_builder: ^0.7.0
  responsive_framework: ^1.1.0
  syncfusion_flutter_pdfviewer: ^28.1.37
  webview_flutter: ^4.0.2

  #third-party
  app_settings: ^5.1.1
  permission_handler: ^11.0.0
  flutter_inappwebview: ^6.2.0-beta.2

  #core
  cached_network_image: ^3.2.3
  go_router: ^15.1.3

  #util

  flutter_image_compress: ^2.0.4
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  flutter_svg: ^2.0.9

  #firebase
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  firebase_remote_config: ^5.0.2
  firebase_analytics: ^11.3.6
  firebase_messaging: ^15.0.2
  cloud_firestore: ^5.6.0
  firebase_crashlytics: ^4.0.2
  firebase_ui_firestore: ^1.7.1
  cloud_functions: ^5.0.2

  #database
  shared_preferences: ^2.2.1
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13

  #package
  image_picker: ^1.0.4
  image_cropper: ^8.0.2
  share_plus: ^10.0.2
  screenshot: ^3.0.0
  path_provider: ^2.1.1
  add_2_calendar: 3.0.1
  in_app_review: ^2.0.8
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.3
  whatsapp_unilink: ^2.1.0
  kartal: ^4.1.0
  collection: ^1.18.0

  # ui
  dotted_border: ^2.0.0+3
  shimmer: ^3.0.0
  sliver_snap: ^2.0.0
  font_awesome_flutter: ^10.5.0

  carousel_slider: ^5.0.0
  flutter_speed_dial: ^7.0.0

  #Flutter
  video_player: ^2.7.2

  #Location
  google_maps_flutter: ^2.6.1
  intl: ^0.20.2

  # JSON
  json_annotation: ^4.8.0

  life_shared:
    git:
      url: https://github.com/VB-CORE/life_shared.git
      ref: v5.4.7

  file_picker: ^8.0.5
  sliver_tools: ^0.2.12
  hugeicons: ^0.0.7

dependency_overrides:
  device_info_plus: ^11.4.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter

  logger: ^2.0.1
  json_serializable: ^6.6.1
  very_good_analysis: ^7.0.0

  riverpod_generator: ^2.3.8
  go_router_builder: ^3.0.0
flutter_gen:
  output: lib/product/generated/
  integrations:
    lottie: true
    flutter_svg: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

scripts:
  lang: flutter pub run easy_localization:generate  -O lib/product/init/language -f keys -o locale_keys.g.dart --source-dir assets/translations
  dartBuild: flutter pub run build_runner build --delete-conflicting-outputs
  build: flutter pub run build_runner build
  buildForce: flutter pub run build_runner build --delete-conflicting-outputs
  pubGet: sh ./scripts/pub_get.sh
  watchBuild: flutter pub run build_runner watch --delete-conflicting-outputs
  general: rps build && rps lang
  podUpdate: cd ios && pod update && cd ..
  fios: flutter clean && flutter pub get && cd ios && pod install && cd ..
  emulator: firebase emulators:start --import=./emulator-data --export-on-exit=./emulator-data

  updateIcon: sh ./scripts/update_icon.sh
flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/
    - assets/docs/
    - assets/lottie/
    - assets/images/
    - assets/svg/
